### ISSUE TITLE
There is something wrong with this gem "rbnacl-libsodium (1.0.15.1)"

### ISSUE THREAD

**Issue by barre121** [Deathlive/Storm#2]
This what is happening "Fetching rbnacl-libsodium 1.0.15.1
Installing rbnacl-libsodium 1.0.15.1 with native extensions" but it can't install anymore.
The problem is here

make: /bin/sh: Command not found
make: *** [Makefile:511: all-recursive] Error 127
extconf.rb:4:in `sys': ERROR: 'make' failed (RuntimeError)
        from extconf.rb:24:in `block in <main>'
        from extconf.rb:21:in `chdir'
        from extconf.rb:21:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in
/data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/rbnacl-libsodium-1.0.15.1
for inspection.
Results logged to
/data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/extensions/aarch64-linux/2.4.0/rbnacl-libsodium-1.0.15.1/gem_make.out

An error occurred while installing rbnacl-libsodium
(1.0.15.1), and Bundler cannot continue.
Make sure that `gem install rbnacl-libsodium -v '1.0.15.1'`
succeeds before bundling.

I am new to all these please help.

**Comment by Demigoddd** [comment]
@barre121 
`pkg install autoconf bison clang coreutils curl findutils git apr apr-util libffi-dev libgmp-dev libpcap-dev postgresql-dev readline-dev libsqlite-dev openssl-dev libtool libxml2-dev libxslt-dev ncurses-dev pkg-config postgresql-contrib wget make ruby-dev libgrpc-dev termux-tools ncurses ncurses-utils libsodium-dev termux-exec`

special `pkg install libsodium libsodium-dev`

I just installed, without any problems.
![default](https://user-images.githubusercontent.com/29791715/32987757-990161e0-cd0d-11e7-83c9-efe2a6f96466.png)

If it does not work out, use `termux-chroot`, later `gem install rbnacl-libsodium`.

**Comment by barre121** [comment]
All these tools are already installed and upgraded. I tried it again and it didn't work bro.
   But, what is making confused is that......why Make expects to find...../bin/sh instead of looking for....../data/data/com.termux/files/usr/bin/sh
It can't find.... /bin/bash, because it doesn't exist bro.
As I already told you I am completely newbie....I don't even know how to use ....termux-chroot


Teach me some
Thanks for taking your time with me pal.

**Comment by Demigoddd** [comment]
@barre121 
In linux, `bash` is in `/bin/bash`
But termux `bash` in `/data/data/com.termux/files/usr/bin/bash`

So for beginning in the terminal, just write  `termux-chroot`, To change the location of folders as in `Linux`. Then use the installation command, that is `gem install rbnacl-libsodium`.

**Comment by barre121** [comment]
It stacked 
 [033[1gem install rbnacl-libsodium
Building native extensions. This could take a while...
I waited but nothing happens.
Even if I turn off the '''
WiFi
''' not responding.
What else could I do?

**Comment by barre121** [comment]
Are these the native extensions?

/data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/rbnacl-libsodium-1.0.15.1/vendor/libsodium/dist-build
> ls
Makefile             emscripten-symbols.def
Makefile.am          emscripten.sh*
Makefile.in          generate-emscripten-symbols.sh*
android-arm.sh*      ios.sh*
android-armv7-a.sh*  msys2-win32.sh*
android-armv8-a.sh*  msys2-win64.sh*
android-build.sh*    nativeclient-pnacl.sh*
android-mips32.sh*   nativeclient-x86.sh*
android-mips64.sh*   nativeclient-x86_64.sh*
android-x86.sh*      osx.sh*                             android-x86_64.sh*
>

Inside "' android-arm.sh  "' this is what I see....

cat android-build.sh*
#! /bin/sh

if [ -z "$NDK_PLATFORM" ]; then
  export NDK_PLATFORM="android-16"...........


So what if i change   /bin/sh  to /data/data/com.termux/files/usr/bin/sh


Inorder let the 'make' program identify 
/bin/s


Sorry my ignorance and bad english bro.

**Comment by barre121** [comment]
My my phone's architecture "ARM64 (aarch64)
With unknown bootloader.
I don't know!

**Comment by Demigoddd** [comment]
@barre121 
Installation through the `termux-chroot` is slow, goes for a minimum of at least 15-20 minutes, please be patient.

![pic](https://user-images.githubusercontent.com/29791715/33006151-a980a384-cde2-11e7-81d5-06cb8d4d451d.png)

**Comment by barre121** [comment]
Brother, I think my termux-chroot snot working properly, cause is see you are working under 
~ termux-chroot

But me when launch termux-chroot looks for other commands and fails
at last it comes up with 
these
  

           32m]:[033[1: command not found
31m]w$: command not found
[033[1

[033[1.......is what I have instead of...... termux-chroot..


Any other way to work around with 'gem' 
Manually?

I am sorry for getting you confused

**Comment by Demigoddd** [comment]
I also sometimes get this error, but it does not fail and `termux-chroot` works fine.
Just output `termux chroot` and `gem Install rbnacl-libsodium` and wait.

Or you can try to install rbnacl-libsodium independently, via the wiki.
[rbnacl-libsodium](https://wiki.termux.com/wiki/Metasploit_Framework#rbnacl-libsodium)
Just this is an old version, you have to change the version of `rbnacl-libsodium` in the file `Gemfile.lock`
To the version you install from the wiki, that is, `1.0.13`.

But I advise you to start simply using the installation via `termux-chroot`, Error `32m]:[033[1: comman`d not found this is not a problem.And it does not interfere with the `termux-chroot`,

**Comment by barre121** [comment]
the other step comes up with error,
I think i need to reinstall termux, cause i have messed up things.
First time i installed termux, metasploit worked, i removed the directory accidentally, from that day nothing works, even from the previous source that worked for me before.
But i need a way to backup every think inside termux including directories in$HOME.

I am on the verge to lose my hair, buddy.

You tried to help me, no matter  how bad my english is.
Thanks
